WebApp/WebApp/Controllers/DeliveryPointsController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System;
using System.Linq;
using System.Threading.Tasks;
using WebApp.Domain.Models;
using WebApp.Infrastructure;
using WebApp.Models;
using WebApp.Services;

namespace WebApp.Controllers
{
    [Authorize]
    public class DeliveryPointsController : Controller
    {
        private readonly ILogger<DeliveryPointsController> _logger;
        private readonly UserManager<User> _userManager;
        private readonly IUserService _userService;
        private readonly IWarehouseService _warehouseService;
        private readonly IDeliveryPointService _deliveryPointService;
        private readonly IAuthenticationSchemeProvider _schemeProvider;
        private readonly ICompanyService _companyService;
        private readonly ApplicationDbContext _context;

        public DeliveryPointsController(
            ILogger<DeliveryPointsController> logger,
            IAuthenticationSchemeProvider schemeProvider,
            UserManager<User> userManager,
            IUserService userService,
            IDeliveryPointService deliveryPointService,
            IWarehouseService warehouseService,
            ICompanyService companyService,
            ApplicationDbContext context)
        {
            _logger = logger;
            _userManager = userManager;
            _userService = userService;
            _warehouseService = warehouseService;
            _deliveryPointService = deliveryPointService;
            _schemeProvider = schemeProvider;
            _companyService = companyService;
            _context = context;
        }

        // GET: DeliveryPoints
        public async Task<IActionResult> Index()
        {
            return View(await _deliveryPointService.GetAllAsync());
        }

        // GET: DeliveryPoints/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var deliveryPoint = await _deliveryPointService.GetAsync((Guid) id);
            if (deliveryPoint == null)
            {
                return NotFound();
            }

            return View(deliveryPoint);
        }

        // GET: DeliveryPoints/Create
        public IActionResult Create()
        {
            ViewData["WarehouseId"] = new SelectList(_context.Warehouses, "Id", "Name");
            return View();
        }

        // POST: DeliveryPoints/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,WarehouseId,Address,PhoneNumber,Id")]
            DeliveryPointDto deliveryPoint)
        {
            if (ModelState.IsValid)
            {
                deliveryPoint.Id = Guid.NewGuid();
                await _deliveryPointService.CreateAsync(deliveryPoint);
                return RedirectToAction(nameof(Index));
            }

            ViewData["WarehouseId"] = new SelectList(_context.Warehouses, "Id", "Name", deliveryPoint.WarehouseId);
            return View(deliveryPoint);
        }

        // GET: DeliveryPoints/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var deliveryPoint = await _deliveryPointService.GetAsync((Guid) id);
            if (deliveryPoint == null)
            {
                return NotFound();
            }

            ViewData["WarehouseId"] = new SelectList(await _warehouseService.GetAllAsync(), "Id", "Name",
                deliveryPoint.WarehouseId);
            return View(deliveryPoint);
        }

        // POST: DeliveryPoints/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Name,WarehouseId,Address,PhoneNumber,Id")]
            DeliveryPointDto deliveryPoint)
        {
            if (id != deliveryPoint.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _deliveryPointService.UpdateAsync(deliveryPoint);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!await DeliveryPointExists(deliveryPoint.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                return RedirectToAction(nameof(Index));
            }

            ViewData["WarehouseId"] = new SelectList(await _warehouseService.GetAllAsync(), "Id", "Name",
                deliveryPoint.WarehouseId);
            return View(deliveryPoint);
        }

        // GET: DeliveryPoints/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var deliveryPoint = await _deliveryPointService.GetAsync((Guid) id);
            await _deliveryPointService.RemoveAsync(deliveryPoint.Id);

            return RedirectToAction(nameof(Index));
        }

        // POST: DeliveryPoints/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var deliveryPoint = await _context.DeliveryPoints.FindAsync(id);
            return RedirectToAction(nameof(Index));
        }

        private async Task<bool> DeliveryPointExists(Guid id)
        {
            return (await _deliveryPointService.GetAllAsync()).Any(e => e.Id == id);
        }
    }
}

WebApp/WebApp/Views/DeliveryPoints/Create.cshtml
@model DeliveryPointDto

@{
    ViewData["Title"] = "Create";
}

<div class="login-form">
    <form asp-action="Create" method="post">
        <div class="avatar">
            <i class="material-icons">home</i>
        </div>
        <h4 class="modal-title">Dodajanje dostavne točke</h4>
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <input type="text" asp-for="Name" class="form-control" placeholder="Naziv" required="required">
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="form-group">
            <select asp-for="WarehouseId" class="form-control" asp-items="ViewBag.WarehouseId"></select>
        </div>
        <div class="form-group">
            <input type="text" asp-for="Address" class="form-control" placeholder="Naslov" required="required">
            <span asp-validation-for="Address" class="text-danger"></span>
        </div>
        <div class="form-group">
            <input asp-for="PhoneNumber" class="form-control" placeholder="Tel. številka" />
            <span asp-validation-for="PhoneNumber" class="text-danger"></span>
        </div>
        <input type="submit" class="btn btn-primary btn-block btn-lg" value="Dodaj">
    </form>
</div>

<div class="text-center">
    <a asp-action="Index">Nazaj na seznam</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApp/WebApp/Views/DeliveryPoints/Delete.cshtml
@model DeliveryPointDto

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>DeliveryPoint</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Warehouse)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Warehouse.Name)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

WebApp/WebApp/Views/DeliveryPoints/Details.cshtml
@model DeliveryPointDto

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>DeliveryPoint</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Warehouse)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Warehouse.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

WebApp/WebApp/Views/DeliveryPoints/Edit.cshtml
@model DeliveryPointDto

@{
    ViewData["Title"] = "Edit";
}


<div class="login-form">
    <form asp-action="Edit">
        <div class="avatar">
            <i class="material-icons">home</i>
        </div>
        <h4 class="modal-title">Urejanje dostavne točke</h4>
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <input type="text" asp-for="Name" class="form-control" placeholder="Naziv" required="required">
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="form-group">
            <select asp-for="WarehouseId" class="form-control" asp-items="ViewBag.WarehouseId"></select>
        </div>
        <div class="form-group">
            <input type="text" asp-for="Address" class="form-control" placeholder="Naslov" required="required">
            <span asp-validation-for="Address" class="text-danger"></span>
        </div>
        <div class="form-group">
            <input asp-for="PhoneNumber" class="form-control" placeholder="Tel. številka" />
            <span asp-validation-for="PhoneNumber" class="text-danger"></span>
        </div>
        <input type="submit" class="btn btn-primary btn-block btn-lg" value="Shrani">
    </form>
</div>

<div class="text-center">
    <a asp-action="Index">Nazaj na seznam</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApp/WebApp/Views/DeliveryPoints/Index.cshtml
@model IEnumerable<DeliveryPointDto>

@{
    ViewData["Title"] = "Index";
}

<div class="container">
    <div class="table-wrapper">
        <div class="table-title">
            <div class="row">
                <div class="col-sm-5">
                    <h2>Dostavne točke</h2>
                </div>
                <div class="col-sm-7">
                    <a asp-controller="DeliveryPoints" asp-action="Create" class="btn btn-primary">
                        <i class="material-icons">&#xE147;</i> <span>Dodaj dostavno točko</span>
                    </a>
                </div>
            </div>
        </div>
        <table class="table table-striped table-hover">
            <thead>
            <tr>
                <th>Naziv</th>
                <th>Naslov</th>
                <th>Skladišče</th>
                <th>Tel. številka</th>
                <th>Status</th>
                <th>Akcije</th>
            </tr>
            </thead>
            <tbody>
            @foreach (var deliveryPoint in Model)
            {
                <tr>
                    <td>@Html.DisplayFor(modelItem => deliveryPoint.Name)</td>
                    <td>@Html.DisplayFor(modelItem => deliveryPoint.Address)</td>
                    <td>@Html.DisplayFor(modelItem => deliveryPoint.Warehouse.Name)</td>
                    <td>@Html.DisplayFor(modelItem => deliveryPoint.PhoneNumber)</td>
                    <td><span class="status text-success">&bull;</span> Obratuje</td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@deliveryPoint.Id" class="settings" title="Uredi" data-toggle="tooltip">
                            <i class="material-icons">&#xE8B8;</i>
                        </a>
                        <a asp-controller="DeliveryPoints" asp-action="Delete" asp-route-id="@deliveryPoint.Id" class="delete" title="Odstrani" data-toggle="tooltip">
                            <i class="material-icons">&#xE5C9;</i>
                        </a>
                    </td>
                </tr>
            }
            </tbody>
        </table>
        <div class="clearfix">
            <div class="hint-text">Prikazanih <b>@Model.Count()</b> od <b>@Model.Count()</b> zapisov.</div>
            <ul class="pagination">
                <li class="page-item disabled">
                    <a href="#">Nazaj</a>
                </li>
                <li class="page-item active">
                    <a href="#" class="page-link">1</a>
                </li>
                <li class="page-item">
                    <a href="#" class="page-link">2</a>
                </li>
                <li class="page-item">
                    <a href="#" class="page-link">3</a>
                </li>
                <li class="page-item">
                    <a href="#" class="page-link">4</a>
                </li>
                <li class="page-item">
                    <a href="#" class="page-link">5</a>
                </li>
                <li class="page-item">
                    <a href="#" class="page-link">Naprej</a>
                </li>
            </ul>
        </div>
    </div>
</div>